# Generated by Django 2.2.2 on 2019-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_detail',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('salary', models.FloatField()),
                ('department', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('joined', models.DateTimeField()),
            ],
        ),
    ]
