# Generated by Django 2.2.2 on 2019-06-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='c_color',
            new_name='car_color',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='c_fuel',
            new_name='car_fuel',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='c_id',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='c_name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='c_variant',
            new_name='car_variant',
        ),
    ]
